# Generated by Django 2.2.19 on 2022-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
    ]
