# Generated by Django 2.2.19 on 2022-09-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reach',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildup.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
    ]
