# Generated by Django 2.2.19 on 2022-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0002_auto_20220904_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
