# Generated by Django 2.2.19 on 2022-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0003_auto_20220904_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reach',
            name='reach',
            field=models.FloatField(verbose_name='охват'),
        ),
    ]
