# Generated by Django 2.2.19 on 2022-09-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0004_auto_20220904_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reach',
            name='unit',
        ),
    ]
