# Generated by Django 2.2.19 on 2022-09-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0005_remove_reach_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reach',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildup.Unit'),
            preserve_default=False,
        ),
    ]
