# Generated by Django 2.2.19 on 2022-09-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0006_reach_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reach',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='buildup.Unit'),
        ),
    ]
