# Generated by Django 2.2.19 on 2022-09-06 13:20

import buildup.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0007_auto_20220906_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reach',
            name='reach',
            field=models.FloatField(validators=[buildup.validators.reach_value_validator], verbose_name='охват'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(null=True, validators=[buildup.validators.unit_value_validator], verbose_name='Рейтинг'),
        ),
    ]
